<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>MockSmtp</title>

    <link rel="stylesheet" href="./bootstrap/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="./jquery-ui-1.11.4.custom/jquery-ui.min.css" type="text/css" />
    <script type="text/javascript" src="./jquery-1.10.2.min.js" ></script>
    <script type="text/javascript" src="./jquery-ui-1.11.4.custom/jquery-ui.min.js" ></script>
    <script type="text/javascript" src="./bootstrap/js/bootstrap.min.js" ></script>
    <script type="text/javascript" src="./script.js" ></script>
    <link rel="shortcut icon" href="./favicon.ico" >

<style type="text/css">
.table-bordered th {
    background-color: #000;
    color: #fff;
    font-weight: bold;
    padding: 6px 8px;
    text-align: center;
}

.text-pre {
    white-space: pre-wrap;
    word-break: break-all;
    word-wrap: break-word;
}

.search_area {
    margin-bottom: 20px;
    border-radius: 10px;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;
    border: 2px solid #999;
    padding: 10px;
}

.mail_area {
    border-radius: 10px;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;
    border: 2px solid #999;
    padding: 10px;
}
</style>

</head>
<body>
    <div class="container">
        <div class="row">
            <h2>MockSMTP</h2>
        </div>

        <hr>

        <div class="row search_area">
            <form action=".">
                <table class="table table-bordered">
                    <tr>
                        <th style="width:10%;">FROM</th>
                        <td style="width:39%;"><input type="text" name="from" class="form-control error_disable" value="<?php echo h($this->params['from']);?>"></td>
                        <th style="width:10%;">TO</th>
                        <td style="width:39%;"><input type="text" name="to" class="form-control error_disable" value="<?php echo h($this->params['to']);?>"></td>
                    </tr>
                    <tr>
                        <th>CC</th>
                        <td><input type="text" name="cc" class="form-control error_disable" value="<?php echo h($this->params['cc']);?>"></td>
                        <th>BCC</th>
                        <td><input type="text" name="bcc" class="form-control error_disable" value="<?php echo h($this->params['bcc']);?>"></td>
                    </tr>
                    <tr>
                        <th>SUBJECT</th>
                        <td><input type="text" name="subject" class="form-control error_disable" value="<?php echo h($this->params['subject']);?>"></td>
                        <th>DATE</th>
                        <td>
                            <div class="form-inline">
                                <div class="form-group">
                                    <input type="text" name="date_from" class="form-control datepicker" value="<?php echo h(App::formatDate($this->params['date_from']));?>">
                                </div>
                                <div class="form-group">
                                    ～
                                </div>
                                <div class="form-group">
                                    <input type="text" name="date_to" class="form-control datepicker" value="<?php echo h(App::formatDate($this->params['date_to']));?>">
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th></th>
                        <td colspan="3">
                            <label><input type="checkbox" name="file" class="error_disable" value="1" <?php if($this->params['file']):?>checked="checked"<?php endif;?>> 添付ファイルあり</label>
                            <label><input type="checkbox" name="error_flg" value="1" <?php if($this->params['error_flg']):?>checked="checked"<?php endif;?>> エラーのみ表示</label>
                        </td>
                    </tr>
                </table>

                <div class="text-center">
                    <input type="submit" class="btn btn-primary" value="検索">
                </div>
            </form>
        </div>

        <hr>

        <?php include __DIR__ . '/../../parts/pagination.phtml'; ?>

        <div class="row">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>FROM</th>
                        <th>TO</th>
                        <th>SUBJECT</th>
                        <th style="width: 160px;">DATETIME</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach($this->rowset as $row): ?>
                        <tr>
                            <?php if($row['error_flg']):?>
                                <td colspan="3" class="mail_subject">
                                    受信時エラー : <?php echo h($row['error_msg']);?>
                                </td>
                            <?php else:?>
                                <td>
                                    <?php if(isset($this->from_address[$row['mail_id']])):?>
                                        <?php foreach($this->from_address[$row['mail_id']] as $from_address): ?>
                                            <div><?php echo h($from_address['address']);?></div>
                                        <?php endforeach;?>
                                    <?php endif;?>
                                </td>
                                <td>
                                    <?php if(isset($this->to_address[$row['mail_id']])):?>
                                        <?php foreach($this->to_address[$row['mail_id']] as $to_address): ?>
                                            <div><?php echo h($to_address['address']);?></div>
                                        <?php endforeach;?>
                                    <?php endif;?>
                                </td>
                                <td class="mail_subject">
                                    <?php echo h($row['subject']); ?>
                                </td>
                            <?php endif;?>
                            <td><?php echo h(App::formatDatetime($row['receive_date'])); ?></td>
                            <td>
                                <a class="btn btn-default show_detail" href="#" data-id="<?php echo $row['mail_id'];?>" role="button">
                                    詳細
                                </a>
                            </td>
                        </tr>

                    <?php endforeach;?>
                </tbody>
            </table>
        </div>

        <?php include __DIR__ . '/../../parts/pagination.phtml'; ?>

        <div class="modal fade" id="mail_detail" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content" style="width:1000px; margin-left: -200px;">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modal-label"></h4>
              </div>
              <div class="modal-body"></div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</body>
</html>