<?php if($this->pages->pageCount > 1): ?>
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">

            <?php if(isset($this->pages->previous)):?>
                <li>
                    <a href="?<?php echo http_build_query($this->params);?>&page=<?php echo $this->pages->previous;?>">&laquo;</a>
                </li>
            <?php else:?>
                <li class="disabled">
                    <a onclick="return false;" href="#">&laquo;</a>
                </li>
            <?php endif;?>

            <?php foreach($this->pages->pagesInRange as $page): ?>
                <?php if($page==$this->pages->current):?>
                    <li class="active">
                        <a onclick="return false;" href="#"><?php echo $page;?></a>
                    </li>
                <?php else:?>
                    <li>
                        <a href="?<?php echo http_build_query($this->params);?>&page=<?php echo $page;?>"><?php echo $page;?></a>
                    </li>
                <?php endif;?>
            <?php endforeach; ?>

            <?php if(isset($this->pages->next)):?>
                <li>
                    <a href="?<?php echo http_build_query($this->params);?>&page=<?php echo $this->pages->next;?>">&raquo;</a>
                </li>
            <?php else:?>
                <li class="disabled">
                    <a onclick="return false;" href="#">&raquo;</a>
                </li>
            <?php endif;?>

        </ul>
    </div>
</div>
<?php endif; ?>